### ISSUE TITLE
您好，想问一下wood格式的文件是运用了什么插件嘛，最近也在研究榫卯的项目，想借鉴一下

### ISSUE THREAD

**Issue by kevin814999654** [IanLi1999/Interlocked#2]
您好，想问一下wood格式的文件是运用了什么插件嘛，最近也在研究榫卯的项目，想借鉴一下

**Comment by jazli1999** [comment]
> 您好，想问一下wood格式的文件是运用了什么插件嘛，最近也在研究榫卯的项目，想借鉴一下

没有用插件，是当时随便取了一个后缀名。内容是木块渲染的坐标，文件解析的代码应该是这里：https://github.com/jazli1999/Interlocked/blob/93edb68628eeff2cf8f35d9549d6ec9d8170d165/%E5%8C%A0%E9%94%81/Assets/Script/gameplay/gamemanager1.cs#L132

当年写得比较乱，凑合看
